blank_issues_enabled: false
contact_links:
  - name: ‚ùì Usage question
    url: https://github.com/simonbesnard1/gedidb/discussions
    about: |
      Ask questions and discuss with other community members here.
      If you have a question like "How do I concatenate a list of datasets?" then
      please include a self-contained reproducible example if possible.